version: "3.7"
services:
  app: &app
    build:
      context: .
      target: development
    volumes:
      - .:/opt/app
    tmpfs:
      - /opt/app/tmp/cache
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:alpine3.18
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres:

networks:
  default:
    name: projects
    ipam:
      driver: default
      config:
        - subnet: "69.0.0.69/24"
